name: AI Test Generation

on:
  issues:
    types: [opened, labeled, edited]

jobs:
  generate-tests:
    if: contains(github.event.issue.labels.*.name, 'ai-test-gen')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout target repository
      uses: actions/checkout@v4
      with:
        path: target-repo

    - name: Checkout AI tools
      uses: actions/checkout@v4
      with:
        repository: SwathantraPulicherla/ai-c-test-generator
        path: ai-tools
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install AI test generator dependencies
      run: |
        cd ai-tools/ai-c-test-generator
        pip install -r requirements.txt

    - name: Generate AI tests
      env:
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      run: |
        cd target-repo
        python ../ai-tools/ai-c-test-generator/generator.py --api-key "$GOOGLE_API_KEY" --source src/

    - name: Check for changes
      id: verify-changed-files
      run: |
        cd target-repo
        if [ -n "$(git status --porcelain)" ]; then
          echo "changes=true" >> $GITHUB_OUTPUT
        else
          echo "changes=false" >> $GITHUB_OUTPUT
        fi

    - name: Commit and push generated tests
      if: steps.verify-changed-files.outputs.changes == 'true'
      run: |
        cd target-repo
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "🤖 AI-generated unit tests

        Generated by AI Test Generator
        Triggered by issue #${{ github.event.issue.number }}"
        git push

    - name: Comment on issue
      if: steps.verify-changed-files.outputs.changes == 'true'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '✅ AI test generation completed! Tests have been generated and committed to the repository.'
          })

    - name: Comment on issue (no changes)
      if: steps.verify-changed-files.outputs.changes == 'false'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'ℹ️ AI test generation completed, but no new tests were generated. This might indicate that tests already exist or no suitable source files were found.'
          })